### ISSUE TITLE
MCP and GameME

### ISSUE THREAD

**Issue by Alex-Thunderhunter** [DosMike/SM-MetaChatProcessor#3]
Hello,
It seems that any event that happens via GameME that is announced in chat doesn't show up when MCP is installed. So, like if someone gets a kill, it doesn't show them in chat how many points they got from that kill. Or if they captured a point it doesn't show up in chat. I've tried every configuration option independently and all together to no avail.

**Comment by DosMike** [comment]
For what game / gameme version?

**Comment by Alex-Thunderhunter** [comment]
TF2/GameMe v4.8

**Comment by DosMike** [comment]
Chat messages using SayText2 seem to be only sent on CSGO/CSS/DODS, not on TF2. I'm not paying 5 bucks just to install gameme on my dev server, so I'd appreciate if you could attach some screenshots on what those messages look like, so I can better analyze their plugin.

**Comment by Alex-Thunderhunter** [comment]
Sorry it took me so long to get the screenshot - I ended up taking some time off on a few projects.

These are the commands issued via rcon from GameMe:
`rcon from "144.76.139.104:49630": command "gameme_psay "4" 1 "x04gameME:x01 x07FF3E3EQuantumXYZx01 (955) got 5 points for x04Point Captured""`

`rcon from "144.76.139.104:49630": command "gameme_psay "4,5" 1 "x04gameME:x01 x07FF3E3ERedx01 got 2 points for x04Point Captured""`

![20231227030732_1](https://github.com/DosMike/SM-MetaChatProcessor/assets/25190612/bcb72ee6-aaf8-436b-b6f9-097c817f5c1f)

**Comment by DosMike** [comment]
Thanks, Hope 23w52a helps.
Please get back to me if it's still broken (or i broke something :D)

**Comment by Alex-Thunderhunter** [comment]
That worked - Thanks
